#  yml不能使用制表符tab 只能用普通空格进行缩进 
# 设置值使用 :空格(值) 
server:
  port: 8002

# 定义当前服务名
spring:
  application:
    name: sorder
# 配置Eureka 服务器的地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka
      
#yml支持同一文件内部的配置块，使用 --- 分隔每一个配置块, 每个配置块都必须有个名字, 没有名字作为默认配置块
---
server:
  port: 8007
#配置块  
spring:
  profiles:  sorder8007
  
---
server:
  port: 8008
#配置块  
spring:
  profiles:  sorder8008     

      


  
    



    
    

