#  yml不能使用制表符tab 只能用普通空格进行缩进 
# 设置值使用 :空格(值) 
server:
  port: 8002

# 定义当前服务名
spring:
  application:
    name: sorder
# 配置Eureka 服务器的地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka

      


  
    



    
    

