server:
  port: 8004
  
# 定义当前服务名
spring:
  application:
    name: crbook
    
  datasource:
    url: jdbc:mysql://127.0.0.1/c85-s3-crbook?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: a
    driver-class-name: com.mysql.jdbc.Driver
    
#日志配置
logging:
  level:
    com:
      zj:
        C85S3CRBookbook:
          dao: debug
          web: warn