#  yml不能使用制表符tab 只能用普通空格进行缩进 
# 设置值使用 :空格(值) 
server:
  port: 80
  
#日志配置
logging:
  level:
    com:
      zj:
        C85S3Blog:
          dao: debug
          web: warn
          
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/c85-s3-blog?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: a
    driver-class-name: com.mysql.jdbc.Driver
    
  servlet:
    multipart:
      #总文件大小
      max-request-size:  10MB
      #单文件大小
      max-file-size:  10MB
      
  #邮件发送  YML配置规则：如果某个阶段有重复配置情况，必须合并   
  mail:
       #邮箱服务器地址
       host: smtp.qq.com
       #用户名
       username: 1529072552@qq.com
       #密码
       password: hcnpmgrdgzkrbaci
       default-encoding: UTF-8 

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:       
             
      
#用户邮箱自定义配置
mail:
  fromMail: 
    addr: 1529072552@qq.com
  
  
     
      
      


  
    



    
    

