#  yml不能使用制表符tab 只能用普通空格进行缩进 
# 设置值使用 :空格(值) 
server:
  port: 80
  
#日志配置
logging:
  level:
    com:
      zj:
        C85S3Springboot:
          dao: debug
          web: warn
          
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/c85-s3-blog?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: a
    driver-class-name: com.mysql.jdbc.Driver
    
  servlet:
    multipart:
      #总文件大小
      max-request-size:  10MB
      #单文件大小
      max-file-size:  10MB

  
  
     
      
      


  
    



    
    

