server:
   port: 80
   
# 定义当前服务名
spring:
   application:
      name: zuul
# 配置Eureka 服务器的地址
eureka:
   client:
      serviceUrl:
         defaultZone: http://es1:8000/eureka,http://es2:7999/eureka
         
         
# zuul 路由配置
# http://es3/user/user   ==>   http://es1:8001/user
# http://es3/order/order ==>   http://es1:8002/order

zuul:
  routes:
    # 路由名
    user:
      # 对应接口的地址  /** 表示所有的接口(包含子目录)
      path: /user/**
      serviceId: suser
      
    # 路由名
    order:
      # 对应接口的地址  /** 表示所有的接口(包含子目录)
      path: /order/**
      serviceId: sorder